version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  test:
    executor: node/default
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages
      - run: npm run typecheck
      - run: npm run lint
      - run: npm run test:coverage:summary
workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version:
                - 12.18.0
                - 13.14.0
                - 14.5.0
